name: publiccode.yml update

on:
  schedule:
    - cron:  '30 22 * * 5'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: publiccode-softwareversion-check-action
        uses: italia/publiccode-softwareversion-check-action@v1.2.1
        id: pva
        with:
          remoterepo: "https://git.libreoffice.org/core"
          remove: "libreoffice-"
          filter: "^libreoffice-([0-9]|\\.)+$"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: failure()
        with:
          title: "feat: update softwareVersion ${{ steps.pva.outputs.version }} and date in publiccode.yml"
          branch: feature/publiccode-${{ steps.pva.outputs.version }}
